RADIO_STREAM = "http://stream.rcs.revma.com/ypqt40u0x1zuv"
OLED_I2C_ADDR = 0x3C

GPIO_ENCODER_A = 24
GPIO_ENCODER_B = 23
GPIO_ENCODER_SW = 13

GPIO_BTN_POWER = 5
GPIO_BTN_STOP = 6
GPIO_BTN_PLAY = 12
GPIO_BTN_NEXT = 19
GPIO_BTN_PREV = 26

GPIO_LED_R = 16
GPIO_LED_G = 20
GPIO_LED_B = 21
