# Stałe nazwy dla urządzeń
pcm.dac {
    type hw
    card PCM5102
    device 0
}

pcm.loopback_capture {
    type hw
    card Loopback
    device 1
    subdevice 0
}

pcm.loopback_playback {
    type hw
    card Loopback
    device 0
    subdevice 0
}
