description: Hi-Res Audio Passthrough
devices:
  samplerate: 96000
  chunksize: 2048
  capture:
    type: Alsa
    device: hw:Loopback,1,0
    channels: 2
    format: S32LE
  playback:
    type: Alsa
    device: hw:sndrpihifiberry,0
    channels: 2
    format: S32LE
filters:
  bass:
    type: Biquad
    description: Bass shelf
    parameters:
      type: Highshelf
      freq: 200
      gain: 0
      q: 0.707
  treble:
    type: Biquad
    description: Treble shelf
    parameters:
      type: Lowshelf
      freq: 4000
      gain: 0
      q: 0.707
  loudness:
    type: Biquad
    description: Loudness (low shelf boost)
    parameters:
      type: Lowshelf
      freq: 120
      gain: 0
      q: 0.707
  eq1:
    type: Biquad
    description: 100Hz
    parameters:
      type: Peaking
      freq: 100
      gain: 0
      q: 1.0
  eq2:
    type: Biquad
    description: 500Hz
    parameters:
      type: Peaking
      freq: 500
      gain: 0
      q: 1.0
  eq3:
    type: Biquad
    description: 1kHz
    parameters:
      type: Peaking
      freq: 1000
      gain: 0
      q: 1.0
  eq4:
    type: Biquad
    description: 4kHz
    parameters:
      type: Peaking
      freq: 4000
      gain: 0
      q: 1.0
  eq5:
    type: Biquad
    description: 10kHz
    parameters:
      type: Peaking
      freq: 10000
      gain: 0
      q: 1.0
pipeline:
- type: Filter
  channels:
  - 0
  - 1
  names:
  - bass
  - treble
  - eq1
  - eq2
  - eq3
  - eq4
  - eq5
  - loudness

